package ci

import (
	"fmt"
	"path"
	"sort"
	"strconv"
	"strings"
)

// Checks chooses which kinds of check the pipeline runs. A kind the repo does
// not have is skipped whatever this says.
type Checks struct {
	Lint, Typecheck, Test, Build bool
}

// AllChecks runs every check the repo has.
var AllChecks = Checks{Lint: true, Typecheck: true, Test: true, Build: true}

// Options shape the generated workflow.
type Options struct {
	// BaseBranch is where pushes are also checked; "" means main.
	BaseBranch string
	Checks     Checks
}

// Job is one job of the pipeline, for one package.
type Job struct {
	ID      string
	Package Package
	Steps   []Step
}

// Step is a named command, or an action when Uses is set.
type Step struct {
	Name string
	Run  string
	// Uses runs an action instead of a command; With is its inputs.
	Uses string
	With map[string]string
}

// golangciLint is what Detect records for a Go package with a golangci
// config. The runner has no golangci-lint, so the step is its action.
const golangciLint = "golangci-lint run"

// Jobs lists the pipeline's jobs: one per package that has at least one
// chosen check, in the order Detect found them.
func Jobs(st Stack, checks Checks) []Job {
	var out []Job
	used := map[string]int{}
	for _, p := range st.Packages {
		var steps []Step
		for _, c := range []struct {
			on   bool
			name string
			run  string
		}{
			{checks.Lint, "Lint", p.Lint},
			{checks.Typecheck, "Typecheck", p.Typecheck},
			{checks.Test, "Test", p.Test},
			{checks.Build, "Build", p.Build},
		} {
			switch {
			case !c.on || c.run == "":
			case c.run == golangciLint:
				st := Step{Name: c.name, Uses: "golangci/golangci-lint-action@v8"}
				if p.Dir != "." {
					st.With = map[string]string{"working-directory": p.Dir}
				}
				steps = append(steps, st)
			default:
				steps = append(steps, Step{Name: c.name, Run: c.run})
			}
		}
		if len(steps) == 0 {
			continue
		}
		id := jobID(p)
		used[id]++
		if used[id] > 1 {
			id = fmt.Sprintf("%s-%d", id, used[id])
		}
		out = append(out, Job{ID: id, Package: p, Steps: steps})
	}
	return out
}

// jobID is the language for a root package and the directory otherwise:
// "go", "web", "apps-api".
func jobID(p Package) string {
	if p.Dir == "." {
		return string(p.Language)
	}
	return strings.ReplaceAll(p.Dir, "/", "-")
}

// Render writes the workflow for the jobs, or an error when there is nothing
// to check: an empty workflow would pass every PR while checking nothing.
func Render(jobs []Job, opts Options) ([]byte, error) {
	if len(jobs) == 0 {
		return nil, fmt.Errorf("found nothing to check: no lint, typecheck, test or build in this repository")
	}
	base := opts.BaseBranch
	if base == "" {
		base = "main"
	}
	var b strings.Builder
	b.WriteString("# Generated by `orch ci setup` from this repository's files. Safe to edit:\n")
	b.WriteString("# orch never overwrites it unless asked to (--force).\n")
	b.WriteString("#\n")
	b.WriteString("# Runs on every pull request, which is what orch's auto-PR loop waits on\n")
	b.WriteString("# (config.yaml `vcs:`), and on pushes to the base branch.\n")
	b.WriteString("name: orch-ci\n\n")
	b.WriteString("on:\n  pull_request:\n  push:\n    branches: [" + base + "]\n\n")
	b.WriteString("jobs:\n")
	for i, j := range jobs {
		if i > 0 {
			b.WriteString("\n")
		}
		writeJob(&b, j)
	}
	return []byte(b.String()), nil
}

func writeJob(b *strings.Builder, j Job) {
	p := j.Package
	fmt.Fprintf(b, "  %s:\n", j.ID)
	fmt.Fprintf(b, "    name: %s\n", scalar(jobName(p)))
	b.WriteString("    runs-on: ubuntu-latest\n")
	if p.Dir != "." {
		fmt.Fprintf(b, "    defaults:\n      run:\n        working-directory: %s\n", scalar(p.Dir))
	}
	b.WriteString("    steps:\n")
	b.WriteString("      - uses: actions/checkout@v4\n")
	writeSetup(b, p)
	if p.Install != "" {
		fmt.Fprintf(b, "      - name: Install dependencies\n        run: %s\n", p.Install)
	}
	for _, s := range j.Steps {
		if s.Uses == "" {
			fmt.Fprintf(b, "      - name: %s\n        run: %s\n", s.Name, scalar(s.Run))
			continue
		}
		fmt.Fprintf(b, "      - name: %s\n        uses: %s\n", s.Name, s.Uses)
		if len(s.With) > 0 {
			b.WriteString("        with:\n")
			keys := make([]string, 0, len(s.With))
			for k := range s.With {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				fmt.Fprintf(b, "          %s: %s\n", k, scalar(s.With[k]))
			}
		}
	}
}

// jobName is "node (pnpm)", or "go" where the manager is the language, with
// the directory first for a package below the root.
func jobName(p Package) string {
	name := string(p.Language)
	if p.Manager != name {
		name = fmt.Sprintf("%s (%s)", p.Language, p.Manager)
	}
	if p.Dir == "." {
		return name
	}
	return p.Dir + ": " + name
}

// inRepo turns a path relative to the package into one relative to the repo
// root, which is what an action's `with:` inputs are resolved against
// (working-directory only applies to `run:` steps).
func inRepo(p Package, name string) string {
	if p.Dir == "." {
		return name
	}
	return path.Join(p.Dir, name)
}

func writeSetup(b *strings.Builder, p Package) {
	switch p.Language {
	case Go:
		fmt.Fprintf(b, "      - uses: actions/setup-go@v5\n        with:\n          go-version-file: %s\n", inRepo(p, "go.mod"))
	case Node:
		if p.Manager == "pnpm" {
			b.WriteString("      - uses: pnpm/action-setup@v4\n")
			switch {
			case p.PnpmVersion == "":
				// Without packageManager in package.json the action needs a
				// version to install.
				b.WriteString("        with:\n          version: 9\n")
			case p.Dir != ".":
				// The action reads packageManager from the root package.json
				// unless told where this package's is.
				fmt.Fprintf(b, "        with:\n          package_json_file: %s\n", scalar(inRepo(p, "package.json")))
			}
		}
		if p.Manager == "bun" {
			b.WriteString("      - uses: oven-sh/setup-bun@v2\n")
			return
		}
		version := p.Version
		if version == "" {
			version = "22"
		}
		fmt.Fprintf(b, "      - uses: actions/setup-node@v4\n        with:\n          node-version: %q\n", version)
		if p.Lockfile != "" {
			fmt.Fprintf(b, "          cache: %s\n", p.Manager)
			if p.Lockfile != path.Base(p.Lockfile) {
				fmt.Fprintf(b, "          cache-dependency-path: %s\n", p.Lockfile)
			}
		}
	case Python:
		if p.Manager == "uv" {
			b.WriteString("      - uses: astral-sh/setup-uv@v6\n")
			return
		}
		version := p.Version
		if version == "" {
			version = "3.12"
		}
		fmt.Fprintf(b, "      - uses: actions/setup-python@v5\n        with:\n          python-version: %q\n", version)
	case Rust:
		b.WriteString("      - uses: dtolnay/rust-toolchain@stable\n        with:\n          components: clippy\n")
	}
}

// scalar writes a value YAML reads back as the same string: plain when that
// is safe, double-quoted when it holds something YAML would parse (": ",
// " #", a leading indicator, quotes).
func scalar(v string) string {
	if v == "" || strings.ContainsAny(v[:1], "!&*-?[]{}|>@`\"'%#,:") ||
		strings.Contains(v, ": ") || strings.Contains(v, " #") || strings.ContainsAny(v, "\"'\n") {
		return strconv.Quote(v)
	}
	return v
}
