package dashboard

import (
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/hectorcanaimero/orch/internal/config"
	"github.com/hectorcanaimero/orch/internal/model"
	"github.com/hectorcanaimero/orch/internal/state"
)

// A task's PR and CI reach the SPA, which has had badges waiting for them
// since Sprint F-4 that never rendered: /api/tasks did not send the fields.
// A task with no PR keeps the old shape, fields absent.
func TestTasksCarryTheirPRAndCI(t *testing.T) {
	s := newReadServer(t, &fakeState{tasks: []state.TaskRuntime{
		{ID: "T-1", Status: model.StatusInProgress, PRURL: "https://github.com/o/r/pull/9", CIStatus: "failure", CIAttempts: 2},
		{ID: "T-2", Status: model.StatusTodo},
	}})

	resp := get(t, s, "/api/tasks")
	var got tasksPayload
	decode(t, resp, &got)
	byID := map[string]taskPayload{}
	for _, row := range got.Tasks {
		byID[row.ID] = row
	}
	if r := byID["T-1"]; r.PRURL != "https://github.com/o/r/pull/9" || r.CIStatus != "failure" || r.CIAttempts != 2 {
		t.Errorf("T-1 = %+v, want its PR, failure and 2 attempts", r)
	}

	raw := get(t, s, "/api/task/T-2")
	defer func() { _ = raw.Body.Close() }()
	b, err := io.ReadAll(raw.Body)
	if err != nil {
		t.Fatal(err)
	}
	body := string(b)
	if strings.Contains(body, "pr_url") || strings.Contains(body, "ci_status") {
		t.Errorf("a task with no PR carries PR fields: %s", body)
	}
}

const orchCIWorkflow = `# Generated by orch init
name: orch-ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run tests
        run: go test ./...
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: |
          make build
          echo done
`

func ciServer(t *testing.T, configYAML string, workflows map[string]string) *Server {
	t.Helper()
	root := writeProject(t, configYAML, testTasksJSON)
	dir := filepath.Join(root, ".github", "workflows")
	if err := os.MkdirAll(dir, 0o750); err != nil {
		t.Fatal(err)
	}
	for name, body := range workflows {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	s, err := New(cfg(ProfileOperator, ""), Options{
		Static: spaHandler(t),
		State:  &fakeState{},
		Paths:  config.Paths{Root: root, ID: "demo", ConfigYAML: filepath.Join(root, "config.yaml")},
	})
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	return s
}

func TestCIShowsTheConfiguredPipeline(t *testing.T) {
	s := ciServer(t, `dispatch:
  worktree_mode: true
  base_branch: dev
vcs:
  auto_pr: true
  ci_max_retries: 3
github:
  auto_merge: true
  test_command: go test ./...
`, map[string]string{"orch-ci.yml": orchCIWorkflow, "broken.yaml": "jobs: [unclosed"})

	var got ciPayload
	decode(t, get(t, s, "/api/ci"), &got)

	c := got.Config
	if !c.WorktreeMode || c.BaseBranch != "dev" || !c.AutoPR || c.MaxRetries != 3 || !c.AutoMerge || c.TestCommand != "go test ./..." {
		t.Errorf("config = %+v", c)
	}
	if len(got.Workflows) != 2 {
		t.Fatalf("workflows = %+v, want both files", got.Workflows)
	}
	broken, ci := got.Workflows[0], got.Workflows[1]
	if broken.File != "broken.yaml" || broken.ParseFailed == "" {
		t.Errorf("a workflow that is not YAML must be listed with its error: %+v", broken)
	}
	if ci.Name != "orch-ci" || !ci.OnPRs || strings.Join(ci.Triggers, ",") != "pull_request,push" {
		t.Errorf("orch-ci = %+v", ci)
	}
	if len(ci.Jobs) != 2 || ci.Jobs[0].ID != "test" || ci.Jobs[1].ID != "build" {
		t.Fatalf("jobs = %+v, want test then build, in file order", ci.Jobs)
	}
	if got := strings.Join(ci.Jobs[0].Steps, " | "); got != "actions/checkout@v4 | actions/setup-go@v5 | Run tests" {
		t.Errorf("test steps = %q", got)
	}
	if got := ci.Jobs[1]; strings.Join(got.Needs, ",") != "test" || strings.Join(got.Steps, "") != "make build" {
		t.Errorf("build job = %+v, want needs test and the run's first line as the step", got)
	}
	if len(got.Warnings) != 0 {
		t.Errorf("warnings = %q, want none for a consistent setup", got.Warnings)
	}
}

func TestCIWarnsAboutSettingsThatCannotWork(t *testing.T) {
	s := ciServer(t, `dispatch:
  worktree_mode: false
vcs:
  auto_pr: true
`, map[string]string{"release.yml": "on: [push]\njobs: {}\n"})

	var got ciPayload
	decode(t, get(t, s, "/api/ci"), &got)
	joined := strings.Join(got.Warnings, "\n")
	for _, want := range []string{"worktree_mode is off", "No workflow runs on pull_request"} {
		if !strings.Contains(joined, want) {
			t.Errorf("warnings are missing %q:\n%s", want, joined)
		}
	}
}

// Workflow files and repository settings are the operator's.
func TestCIIsNotAStakeholderRoute(t *testing.T) {
	s := newGatedServer(t, &fakeState{})
	req := httptest.NewRequest(http.MethodGet, "/api/ci", nil)
	req.Header.Set("Authorization", "Bearer test-token-stakeholder")
	rec := httptest.NewRecorder()
	s.Handler().ServeHTTP(rec, req)
	if rec.Code != http.StatusForbidden {
		t.Errorf("stakeholder GET /api/ci = %d, want 403", rec.Code)
	}
}
