package budget

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/hectorcanaimero/orch/internal/state"
)

// The window vector: every answer below is one Python's BudgetGate actually
// gave, at a frozen clock, reading the same two spend rows out of the same
// fixture database. Generated by `testdata/make-window-vector.py` — see that
// file for how the boundaries were chosen and why.
//
// This is the test that matters in the package. The unit tests below it check
// pieces in isolation and would happily agree with a Go implementation that
// had drifted from Python in some consistent way; only a recorded answer from
// the other binary can catch that.

type vectorFile struct {
	Now       string `json:"now"`
	Fixture   string `json:"fixture"`
	Scenarios []struct {
		Name      string                    `json:"name"`
		Why       string                    `json:"why"`
		Providers map[string]vectorProvider `json:"providers"`
		Decisions map[string]struct {
			OK      bool    `json:"ok"`
			Reason  *string `json:"reason"`
			ResetAt *string `json:"reset_at"`
		} `json:"decisions"`
		AllCapped     bool                        `json:"all_capped"`
		EarliestReset *string                     `json:"earliest_reset"`
		Snapshot      map[string]ProviderSnapshot `json:"snapshot"`
	} `json:"scenarios"`
}

type vectorProvider struct {
	WindowHours  float64 `json:"window_hours"`
	TokenBudget  int     `json:"token_budget"`
	ThresholdPct float64 `json:"threshold_pct"`
}

// fixtureBackend opens the Python-written database the state package keeps.
//
// Referenced across package boundaries rather than copied. The file is the
// evidence for "a database Python made opens in Go"; two copies of it would
// be two things to keep in step, and the one that drifted would be the one
// still passing.
func fixtureBackend(t *testing.T) *state.SQLite {
	t.Helper()
	src := filepath.Join("..", "state", "testdata", "orch-py-0.11.0.db")
	raw, err := os.ReadFile(src) // #nosec G304 -- a fixed path into the sibling package's testdata
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	// Copied into the test's own directory because opening it applies WAL and
	// would leave -wal/-shm files next to a tracked fixture.
	dst := filepath.Join(t.TempDir(), "orch.db")
	if err := os.WriteFile(dst, raw, 0o600); err != nil { // #nosec G703 -- dst is t.TempDir()
		t.Fatalf("copy fixture: %v", err)
	}

	db, applied, err := state.Open(context.Background(), dst)
	if err != nil {
		t.Fatalf("open fixture: %v", err)
	}
	if applied != 0 {
		t.Fatalf("fixture needed %d migrations; it should already be current", applied)
	}
	t.Cleanup(func() { _ = db.Close() })
	return state.NewSQLite(db, "billing-api", "/tmp/billing-api")
}

func mustParse(t *testing.T, s string) time.Time {
	t.Helper()
	ts, err := time.Parse(time.RFC3339, s)
	if err != nil {
		t.Fatalf("parse %q: %v", s, err)
	}
	return ts.UTC()
}

func TestWindowMatchesPython(t *testing.T) {
	raw, err := os.ReadFile("testdata/window-vector.json")
	if err != nil {
		t.Fatalf("read window vector: %v", err)
	}
	var vec vectorFile
	if err := json.Unmarshal(raw, &vec); err != nil {
		t.Fatalf("decode window vector: %v", err)
	}
	if len(vec.Scenarios) == 0 {
		t.Fatal("the vector has no scenarios")
	}

	backend := fixtureBackend(t)
	now := mustParse(t, vec.Now)
	ctx := context.Background()

	for _, sc := range vec.Scenarios {
		t.Run(sc.Name, func(t *testing.T) {
			t.Logf("why: %s", sc.Why)

			providers := make(map[string]ProviderBudget, len(sc.Providers))
			for name, p := range sc.Providers {
				// vectorProvider exists only to carry the JSON tags; the
				// fields are ProviderBudget's, so the conversion is the
				// assertion that they have not drifted apart.
				providers[name] = ProviderBudget(p)
			}
			gate := NewGate(backend, &Config{Providers: providers})
			gate.now = func() time.Time { return now }

			for provider, want := range sc.Decisions {
				got, err := gate.CanDispatch(ctx, provider)
				if err != nil {
					t.Fatalf("CanDispatch(%q): %v", provider, err)
				}
				if got.OK != want.OK {
					t.Errorf("CanDispatch(%q).OK = %v, python said %v", provider, got.OK, want.OK)
				}
				wantReason := ""
				if want.Reason != nil {
					wantReason = *want.Reason
				}
				if got.Reason != wantReason {
					t.Errorf("CanDispatch(%q).Reason =\n  %q\npython said\n  %q",
						provider, got.Reason, wantReason)
				}
				if want.ResetAt == nil {
					if !got.ResetAt.IsZero() {
						t.Errorf("CanDispatch(%q).ResetAt = %s, python said null",
							provider, got.ResetAt.Format(resetLayout))
					}
				} else {
					if gotStr := got.ResetAt.UTC().Format(resetLayout); gotStr != *want.ResetAt {
						t.Errorf("CanDispatch(%q).ResetAt = %s, python said %s",
							provider, gotStr, *want.ResetAt)
					}
				}
			}

			capped, err := gate.AllCapped(ctx)
			if err != nil {
				t.Fatalf("AllCapped: %v", err)
			}
			if capped != sc.AllCapped {
				t.Errorf("AllCapped = %v, python said %v", capped, sc.AllCapped)
			}

			reset, err := gate.EarliestReset(ctx)
			if err != nil {
				t.Fatalf("EarliestReset: %v", err)
			}
			if sc.EarliestReset == nil {
				if !reset.IsZero() {
					t.Errorf("EarliestReset = %s, python said null", reset.Format(resetLayout))
				}
			} else if gotStr := reset.UTC().Format(resetLayout); gotStr != *sc.EarliestReset {
				t.Errorf("EarliestReset = %s, python said %s", gotStr, *sc.EarliestReset)
			}

			snap, err := gate.Snapshot(ctx)
			if err != nil {
				t.Fatalf("Snapshot: %v", err)
			}
			if len(snap) != len(sc.Snapshot) {
				t.Fatalf("Snapshot has %d providers, python had %d", len(snap), len(sc.Snapshot))
			}
			for provider, want := range sc.Snapshot {
				got, ok := snap[provider]
				if !ok {
					t.Errorf("Snapshot is missing %q", provider)
					continue
				}
				if got.TokensUsed != want.TokensUsed {
					t.Errorf("Snapshot[%q].TokensUsed = %d, python said %d",
						provider, got.TokensUsed, want.TokensUsed)
				}
				if got.TokenBudget != want.TokenBudget {
					t.Errorf("Snapshot[%q].TokenBudget = %d, python said %d",
						provider, got.TokenBudget, want.TokenBudget)
				}
				// Float equality is right here, not sloppy: both sides compute
				// used/budget*100 on the same two integers in IEEE-754 doubles,
				// so a difference means a different expression, not rounding.
				if got.UsagePct != want.UsagePct {
					t.Errorf("Snapshot[%q].UsagePct = %v, python said %v",
						provider, got.UsagePct, want.UsagePct)
				}
				if got.ThresholdPct != want.ThresholdPct || got.WindowHours != want.WindowHours {
					t.Errorf("Snapshot[%q] window/threshold = %v/%v, python said %v/%v",
						provider, got.WindowHours, got.ThresholdPct,
						want.WindowHours, want.ThresholdPct)
				}
				if got.Capped != want.Capped {
					t.Errorf("Snapshot[%q].Capped = %v, python said %v",
						provider, got.Capped, want.Capped)
				}
				switch {
				case want.ResetAt == nil && got.ResetAt != nil:
					t.Errorf("Snapshot[%q].ResetAt = %q, python said null", provider, *got.ResetAt)
				case want.ResetAt != nil && got.ResetAt == nil:
					t.Errorf("Snapshot[%q].ResetAt = null, python said %q", provider, *want.ResetAt)
				case want.ResetAt != nil && *got.ResetAt != *want.ResetAt:
					t.Errorf("Snapshot[%q].ResetAt = %q, python said %q",
						provider, *got.ResetAt, *want.ResetAt)
				}
			}
		})
	}
}

// The vector's own coverage, asserted rather than assumed.
//
// A vector is only worth what it exercises, and the two cases below are the
// ones a hand-written test set reliably misses: a cutoff landing exactly on a
// row's timestamp, and usage landing exactly on the cap. If a future
// regeneration drops them the comparison above still passes, silently, having
// stopped testing the boundary — which is where the one real bug in this area
// lived.
func TestVectorCoversTheBoundaries(t *testing.T) {
	raw, err := os.ReadFile("testdata/window-vector.json")
	if err != nil {
		t.Fatalf("read window vector: %v", err)
	}
	var vec vectorFile
	if err := json.Unmarshal(raw, &vec); err != nil {
		t.Fatalf("decode window vector: %v", err)
	}

	// The fixture's two spend rows are 23,200 and 50,100 tokens. A scenario
	// reporting 73,300 has included the older row; one reporting 50,100 has
	// excluded it. Both must be present, or the window boundary is untested.
	var sawBoth, sawNewerOnly, sawExactCap bool
	for _, sc := range vec.Scenarios {
		for _, snap := range sc.Snapshot {
			switch snap.TokensUsed {
			case 73_300:
				sawBoth = true
			case 50_100:
				sawNewerOnly = true
			}
			if snap.Capped && snap.TokensUsed == snap.TokenBudget && snap.ThresholdPct == 100 {
				sawExactCap = true
			}
		}
	}
	if !sawBoth {
		t.Error("no scenario puts the cutoff on or before the older row (expected a 73,300 window)")
	}
	if !sawNewerOnly {
		t.Error("no scenario puts the cutoff past the older row (expected a 50,100 window)")
	}
	if !sawExactCap {
		t.Error("no scenario lands usage exactly on the cap")
	}
}
