#!/usr/bin/env python3
"""Generate `window-vector.json` — what Python's BudgetGate actually answers.

Run against the *Python* tree (v0.11.0 + the bug-5 fix, PR #115), with the
`spend` table of `internal/state/testdata/orch-py-0.11.0.db` as the only
source of spend. That fixture has exactly two rows, both `claude`:

    2026-09-01T10:30:00+00:00   18000 in +  5200 out =  23,200
    2026-09-02T11:15:00+00:00   41000 in +  9100 out =  50,100

The window boundaries below are chosen against those two instants on purpose.
`WINDOW_ON_ROW_A` lands the cutoff *exactly* on the older row's timestamp,
which is the case that distinguishes an inclusive window from an exclusive
one — and the case that caught a real bug in `state.SpendSince`, where an
`ORDER BY`/`WHERE` in SQL compared the two timestamp spellings lexically.

Usage:
    python3 internal/budget/testdata/make-window-vector.py \
        > internal/budget/testdata/window-vector.json

The clock is frozen by substituting `budget.datetime`; the module does
`from datetime import datetime`, so the name it calls `.now()` on is a
module-global we can replace. Nothing else in the module needs the real time.
"""

from __future__ import annotations

import json
import shutil
import sys
import tempfile
from datetime import datetime, timedelta, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO))

import orchestrator.budget as B  # noqa: E402
from orchestrator.budget import BudgetConfig, BudgetGate, ProviderBudget  # noqa: E402

FIXTURE = REPO / "internal" / "state" / "testdata" / "orch-py-0.11.0.db"

NOW = datetime(2026, 9, 2, 12, 0, 0, tzinfo=timezone.utc)

# Cutoff lands exactly on the older row's ts (2026-09-01T10:30:00Z).
WINDOW_ON_ROW_A = 25.5
# Six minutes later: the older row falls out.
WINDOW_JUST_PAST_ROW_A = 25.4


class _Frozen(datetime):
    @classmethod
    def now(cls, tz=None):  # noqa: D102
        return NOW if tz is None else NOW.astimezone(tz)


SCENARIOS = [
    {
        "name": "one row in window, under cap",
        "why": "the recent row alone (50,100) sits under an 80,000 cap",
        "providers": {"claude": (1, 100_000, 80)},
    },
    {
        "name": "one row in window, over cap",
        "why": "same single row against a 40,000 cap; reset is that row's ts + window",
        "providers": {"claude": (1, 50_000, 80)},
    },
    {
        "name": "cutoff exactly on the older row",
        "why": "inclusive window: both rows count, so usage is 73,300 not 50,100",
        "providers": {"claude": (WINDOW_ON_ROW_A, 200_000, 80)},
    },
    {
        "name": "cutoff six minutes past the older row",
        "why": "the same query one notch narrower must drop the older row",
        "providers": {"claude": (WINDOW_JUST_PAST_ROW_A, 200_000, 80)},
    },
    {
        "name": "usage exactly equal to the cap",
        "why": "the comparison is `used < cap`, so equality blocks",
        "providers": {"claude": (26, 73_300, 100)},
    },
    {
        "name": "provider with no rows",
        "why": "a configured provider the fixture never spent on reports zero, not an error",
        "providers": {"codex": (3, 400_000, 60)},
    },
    {
        "name": "zero cap with no spend at all",
        "why": (
            "threshold 0 makes the cap 0, and 0 >= 0 blocks with an empty window. "
            "can_dispatch then dates the reset from `now`, while snapshot leaves "
            "reset_at null — the two disagree, and this pins that they do"
        ),
        "providers": {"codex": (3, 400_000, 0)},
    },
    {
        "name": "every configured provider over threshold",
        "why": "all_capped is true only when no provider is free; earliest_reset picks the soonest",
        "providers": {"claude": (1, 50_000, 80), "codex": (3, 400_000, 0)},
    },
    {
        "name": "one provider capped, one free",
        "why": "all_capped false as soon as a single provider can still dispatch",
        "providers": {"claude": (1, 50_000, 80), "opencode": (24, 2_000_000, 70)},
    },
]


def _iso(dt):
    if dt is None:
        return None
    return dt.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def main() -> None:
    B.datetime = _Frozen
    out = {
        "_comment": (
            "Generated by make-window-vector.py against the Python BudgetGate. "
            "Do not hand-edit: regenerate."
        ),
        "now": _iso(NOW),
        "fixture": "internal/state/testdata/orch-py-0.11.0.db",
        "scenarios": [],
    }

    for sc in SCENARIOS:
        with tempfile.TemporaryDirectory() as td:
            state_dir = Path(td)
            # A sqlite-backend project: orch.db and no spend-*.jsonl files.
            shutil.copy(FIXTURE, state_dir / "orch.db")

            cfg = BudgetConfig(providers={
                name: ProviderBudget(
                    window_hours=float(w), token_budget=int(tb), threshold_pct=float(tp)
                )
                for name, (w, tb, tp) in sc["providers"].items()
            })
            gate = BudgetGate(state_dir=state_dir, config=cfg)

            decisions = {}
            for name in sc["providers"]:
                ok, reason, reset_at = gate.can_dispatch(name)
                decisions[name] = {
                    "ok": ok,
                    "reason": reason,
                    "reset_at": _iso(reset_at),
                }
            # An unconfigured provider is never gated, whatever the scenario.
            ok, reason, reset_at = gate.can_dispatch("mysteryprovider")
            decisions["mysteryprovider"] = {
                "ok": ok, "reason": reason, "reset_at": _iso(reset_at),
            }

            out["scenarios"].append({
                "name": sc["name"],
                "why": sc["why"],
                "providers": {
                    name: {
                        "window_hours": float(w),
                        "token_budget": int(tb),
                        "threshold_pct": float(tp),
                    }
                    for name, (w, tb, tp) in sc["providers"].items()
                },
                "decisions": decisions,
                "all_capped": gate.all_capped(),
                "earliest_reset": _iso(gate.earliest_reset()),
                "snapshot": gate.snapshot(),
            })

    json.dump(out, sys.stdout, indent=2, sort_keys=False)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
