#!/usr/bin/env python3
"""Export the event types Python accepts, as `event-types.json`.

    python3 internal/state/testdata/make-event-types.py \
        > internal/state/testdata/event-types.json

Why this is exported rather than transcribed: Go's `eventTypes` is a closed
set and `AppendEvent` rejects anything outside it, so a type Go refuses but
Python emits leaves a run history with a hole in it — no error on either side,
and the first anyone hears of it is a gap in the timeline. `EVENT_TYPES` is
imported from the Python tree, never copied.

`EVENT_TYPES` is the whole answer as of bug 9 (PR #121), which declared the
seven PR/CI types `orch.py` had been emitting against its own validator. Before
that this script carried those seven by hand, because Go had to accept rows the
pending Python fix would write. That half is gone; the list below is only an
assertion that it stays gone.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO))

from orchestrator.state.file_backend import EVENT_TYPES  # noqa: E402

# The seven from bug 9. Asserted, not added: if a revert or a bad merge drops
# one, Go's accepted set would silently shrink with it and the CI poller's
# events would start vanishing again. Failing here is how that stays loud.
BUG_9_TYPES = (
    "pr_created",
    "ci_redispatch",
    "ci_success",
    "pr_auto_merged",
    "pr_auto_merge_failed",
    "ci_failure_retry",
    "ci_blocked",
)

# The four names FR-STATE-7 listed in the plan. Superseded on 2026-08-19
# (docs/history/spec.md:107) and never emitted by any version of orch. Asserted
# absent so that re-reading that stale section cannot put them back.
SUPERSEDED = ("exit_ok", "exit_err", "resume_reset", "dry_run_planned")


def main() -> None:
    missing = [t for t in BUG_9_TYPES if t not in EVENT_TYPES]
    if missing:
        raise SystemExit(
            f"EVENT_TYPES no longer declares {missing}, which orch.py emits. "
            f"Bug 9 (PR #121) declared these; something reverted it."
        )
    resurrected = [t for t in SUPERSEDED if t in EVENT_TYPES]
    if resurrected:
        raise SystemExit(
            f"EVENT_TYPES declares {resurrected}, which no version of orch "
            f"emits — see docs/history/spec.md:107."
        )

    json.dump(
        {
            "_comment": (
                "Generated by make-event-types.py from orchestrator/state/"
                "file_backend.py EVENT_TYPES. Do not hand-edit: regenerate."
            ),
            "all": sorted(EVENT_TYPES),
            "declaration_order": list(EVENT_TYPES),
        },
        sys.stdout,
        indent=2,
    )
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
