package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"html/template"
	"io/fs"
	"math"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/hectorcanaimero/orch/internal/model"
	"github.com/hectorcanaimero/orch/internal/sitegen"
	"github.com/hectorcanaimero/orch/internal/templates"
)

type phaseView struct {
	Name  string
	Tasks []model.Task
}

type templateView struct {
	Name        string
	Summary     string
	Description []string
	Tasks       int
	Phases      []phaseView
	Hours       string
	Models      []string
	SVG         template.HTML
}

// TemplatePages renders the site pages built from orch's own data, keyed by
// path under site/: the template gallery (an index plus one page per shipped
// project template) and the playground, whose starting spec is SampleSpec. The output is deterministic, so a test
// can hold the committed copy in site/templates to it.
func TemplatePages() (map[string][]byte, error) {
	var views []templateView
	for _, t := range templates.List() {
		v, err := viewOf(t)
		if err != nil {
			return nil, err
		}
		views = append(views, v)
	}

	pages := map[string][]byte{}
	var buf bytes.Buffer
	if err := pageTmpl.ExecuteTemplate(&buf, "index", views); err != nil {
		return nil, fmt.Errorf("render template index: %w", err)
	}
	pages["templates/index.html"] = append([]byte(nil), buf.Bytes()...)
	for _, v := range views {
		buf.Reset()
		if err := pageTmpl.ExecuteTemplate(&buf, "page", v); err != nil {
			return nil, fmt.Errorf("render template page %s: %w", v.Name, err)
		}
		pages["templates/"+v.Name+".html"] = append([]byte(nil), buf.Bytes()...)
	}
	buf.Reset()
	if err := pageTmpl.ExecuteTemplate(&buf, "playground", sitegen.SampleSpec); err != nil {
		return nil, fmt.Errorf("render playground: %w", err)
	}
	pages["playground/index.html"] = append([]byte(nil), buf.Bytes()...)
	return pages, nil
}

func viewOf(t templates.Template) (templateView, error) {
	dir, err := templates.Project(t.Name)
	if err != nil {
		return templateView{}, fmt.Errorf("open template %s: %w", t.Name, err)
	}
	raw, err := fs.ReadFile(dir, "tasks.json.tmpl")
	if err != nil {
		return templateView{}, fmt.Errorf("read %s/tasks.json.tmpl: %w", t.Name, err)
	}
	var tf model.TasksFile
	if err := json.Unmarshal([]byte(templates.Render(string(raw), t.Name, time.Time{})), &tf); err != nil {
		return templateView{}, fmt.Errorf("parse %s/tasks.json.tmpl: %w", t.Name, err)
	}

	v := templateView{Name: t.Name, Summary: t.Description, Tasks: len(tf.Tasks), SVG: template.HTML(sitegen.DAGSVG(tf.Tasks))} // #nosec G203 -- DAGSVG escapes every text it writes
	if desc, err := fs.ReadFile(dir, "description.txt"); err == nil {
		for _, line := range strings.Split(string(desc), "\n") {
			if line = strings.TrimSpace(line); line != "" && line != t.Description {
				v.Description = append(v.Description, line)
			}
		}
	}

	hours, models := 0.0, map[string]bool{}
	byPhase := map[int][]model.Task{}
	for _, task := range tf.Tasks {
		hours += task.EstimateHours
		models[task.Model] = true
		byPhase[task.Phase] = append(byPhase[task.Phase], task)
	}
	v.Hours = strconv.FormatFloat(math.Round(hours*10)/10, 'f', -1, 64)
	for m := range models {
		v.Models = append(v.Models, m)
	}
	sort.Strings(v.Models)

	named := map[int]string{}
	for _, p := range tf.Phases {
		named[p.ID] = p.Name
	}
	var ids []int
	for id := range byPhase {
		ids = append(ids, id)
	}
	sort.Ints(ids)
	for _, id := range ids {
		name := named[id]
		if name == "" {
			name = fmt.Sprintf("Phase %d", id)
		}
		v.Phases = append(v.Phases, phaseView{Name: name, Tasks: byPhase[id]})
	}
	return v, nil
}

var pageTmpl = template.Must(template.New("").Funcs(template.FuncMap{
	"hours": func(h float64) string { return strconv.FormatFloat(h, 'f', -1, 64) },
	"join":  strings.Join,
}).Parse(`
{{define "head"}}<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{.}}</title>
  <meta name="theme-color" content="#09090b">
  <link rel="icon" href="../assets/icon.svg" type="image/svg+xml">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,400;9..40,500;9..40,600&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="../style.css">
</head>
<body>
  <a class="skip" href="#main">Skip to content</a>
  <!-- Generated by ` + "`make site-templates`" + ` (cmd/sitegen). Do not edit by hand. -->
  <header class="top wrap">
    <a class="brand" href="../" aria-label="orch home">
      <svg viewBox="0 0 300 180" aria-hidden="true" class="brand-mark"><rect x="0" y="0" width="210" height="24" rx="12" fill="#7c3aed"/><rect x="0" y="46" width="155" height="24" rx="12" fill="#a78bfa"/><rect x="0" y="92" width="232" height="24" rx="12" fill="#7c3aed"/><rect x="0" y="138" width="128" height="24" rx="12" fill="#a78bfa"/></svg>
      <span class="brand-word">orch</span>
    </a>
    <nav aria-label="Primary">
      <a href="../templates/">Templates</a>
      <a href="../playground/">Playground</a>
      <a href="../#install">Install</a>
      <a href="https://github.com/hectorcanaimero/orch">GitHub</a>
    </nav>
  </header>
{{end}}

{{define "foot"}}
  <footer class="foot wrap">
    <p>orch is MIT-licensed and built in the open.</p>
    <nav aria-label="Footer">
      <a href="../">Home</a>
      <a href="../templates/">Templates</a>
      <a href="../playground/">Playground</a>
      <a href="https://github.com/hectorcanaimero/orch/blob/main/docs/MANUAL.en.md">Manual</a>
    </nav>
  </footer>
  <script src="../copy.js" defer></script>
</body>
</html>
{{end}}

{{define "index"}}{{template "head" "Project templates — orch"}}
  <main id="main" class="wrap page">
    <h1 class="page-title">Project templates</h1>
    <p class="lede">Each template is a plan orch can run the day you install it: phases, tasks, the model each task goes to and what it waits for. Start from one with <code>orch init --template &lt;name&gt;</code>, then edit the specs.</p>
    <ul class="gallery">
      {{range .}}<li>
        <a class="gallery-item" href="{{.Name}}.html">
          <span class="gallery-name">{{.Name}}</span>
          <span class="gallery-summary">{{.Summary}}</span>
          <span class="gallery-facts">{{.Tasks}} tasks · {{len .Phases}} phases · {{.Hours}} h estimated</span>
        </a>
      </li>
      {{end}}
    </ul>
  </main>
{{template "foot"}}{{end}}

{{define "playground"}}{{template "head" "Playground — orch"}}
  <main id="main" class="wrap page">
    <h1 class="page-title">Spec to task graph, in your browser</h1>
    <p class="lede">Write the work as a spec — phases, packages, tasks, the model for each and what it waits for. orch's own parser and graph checks run on this page, compiled to WebAssembly: the same code as <code>orch atomize</code> and <code>orch validate</code>. Nothing you type is sent anywhere.</p>
    <div class="pg">
      <div class="pg-input">
        <label for="spec">Spec (markdown)</label>
        <textarea id="spec" spellcheck="false" autocapitalize="off" autocomplete="off">{{.}}</textarea>
        <div class="pg-actions">
          <button class="button" type="button" id="build" disabled>Loading engine…</button>
          <span class="pg-hint">Ctrl+Enter builds. The sample is the <a href="../templates/nextjs-saas.html">nextjs-saas</a> template.</span>
        </div>
      </div>
      <div class="pg-out" id="out" aria-live="polite">
        <p class="pg-empty">Loading orch (about 1.5 MB)…</p>
        <noscript><p class="pg-empty">The playground runs orch in your browser and needs JavaScript and WebAssembly.</p></noscript>
      </div>
    </div>

    <section aria-labelledby="install-title" class="page-section">
      <h2 id="install-title">Run it for real</h2>
      <p class="page-note">Install orch, put the spec under <code>specs/</code> and let <code>orch atomize --apply</code> write <code>tasks.json</code>. Then <code>orch run</code> dispatches every ready task to its agent.</p>
      <div class="copy-cmd">
        <pre class="term" tabindex="0"><code><span data-copy-source>curl -fsSL https://raw.githubusercontent.com/hectorcanaimero/orch/main/scripts/install.sh | sh</span></code></pre>
        <button class="replay" type="button" data-copy hidden>Copy</button>
      </div>
    </section>
  </main>
  <script src="wasm_exec.js"></script>
  <script src="playground.js" defer></script>
{{template "foot"}}{{end}}

{{define "page"}}{{template "head" (printf "%s template — orch" .Name)}}
  <main id="main" class="wrap page">
    <p class="crumb"><a href="./">Templates</a></p>
    <h1 class="page-title">{{.Name}}</h1>
    <p class="lede">{{.Summary}}</p>
    {{range .Description}}<p class="page-note">{{.}}</p>{{end}}
    <dl class="facts">
      <div><dt>Tasks</dt><dd>{{.Tasks}}</dd></div>
      <div><dt>Phases</dt><dd>{{len .Phases}}</dd></div>
      <div><dt>Estimated</dt><dd>{{.Hours}} h</dd></div>
      <div><dt>Routed to</dt><dd><code>{{join .Models ", "}}</code></dd></div>
    </dl>
    <div class="copy-cmd">
      <pre class="term" tabindex="0"><code><span class="c">$</span> <span data-copy-source>orch init --template {{.Name}}</span></code></pre>
      <button class="replay" type="button" data-copy hidden>Copy</button>
    </div>

    <section aria-labelledby="graph-title" class="page-section">
      <h2 id="graph-title">The plan</h2>
      <p class="page-note">A task starts only when everything above it is done. {{if .SVG}}The violet trace is the longest chain: it sets how soon the plan can finish.{{end}}</p>
      <div class="dag-wrap" tabindex="0" role="group" aria-label="Dependency graph, scrollable">{{.SVG}}</div>
    </section>

    <section aria-labelledby="tasks-title" class="page-section">
      <h2 id="tasks-title">Tasks by phase</h2>
      {{range .Phases}}
      <h3>{{.Name}}</h3>
      <div class="table-wrap" tabindex="0">
        <table class="tasks">
          <thead><tr><th scope="col">ID</th><th scope="col">Task</th><th scope="col">Model</th><th scope="col" class="num">Estimate</th><th scope="col">Waits for</th></tr></thead>
          <tbody>
            {{range .Tasks}}<tr><td><code>{{.ID}}</code></td><td class="title">{{.Title}}</td><td><code>{{.Model}}</code></td><td class="num">{{hours .EstimateHours}} h</td><td>{{if .Dependencies}}<code>{{join .Dependencies ", "}}</code>{{else}}—{{end}}</td></tr>
            {{end}}
          </tbody>
        </table>
      </div>
      {{end}}
    </section>

    <p class="page-cta"><a class="button" href="../playground/">Try your own spec in the playground</a></p>
  </main>
{{template "foot"}}{{end}}
`))
