package main

import (
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/hectorcanaimero/orch/internal/templates"
)

// TestTemplateGalleryIsCurrent holds the committed site/templates to what
// the embedded templates render today. A template edit that is not followed
// by `make site-templates` fails here, not on the published site.
func TestTemplateGalleryIsCurrent(t *testing.T) {
	pages, err := TemplatePages()
	if err != nil {
		t.Fatal(err)
	}
	if want := len(templates.List()) + 2; len(pages) != want {
		t.Fatalf("pages = %d, want %d (gallery index + one per template + playground)", len(pages), want)
	}
	site := os.DirFS(filepath.Join("..", "..", siteDir))
	for name, body := range pages {
		got, err := fs.ReadFile(site, name)
		if err != nil {
			t.Fatalf("%s: %v — run `make site-templates`", name, err)
		}
		if string(got) != string(body) {
			t.Errorf("%s is stale — run `make site-templates`", name)
		}
	}
	entries, err := fs.ReadDir(site, "templates")
	if err != nil {
		t.Fatal(err)
	}
	for _, e := range entries {
		if _, ok := pages["templates/"+e.Name()]; !ok {
			t.Errorf("%s is not generated by any template — delete it or run `make site-templates` after removing it", e.Name())
		}
	}
}

func TestTemplatePageContent(t *testing.T) {
	pages, err := TemplatePages()
	if err != nil {
		t.Fatal(err)
	}
	page := string(pages["templates/nextjs-saas.html"])
	for _, want := range []string{
		"orch init --template nextjs-saas",
		"Next.js 14 SaaS",
		"<dd>6</dd>",   // tasks
		"<dd>4 h</dd>", // estimate: 0.5+0.6+0.5+0.8+1.0+0.6
		`class="dag"`,
		"F2 — Supabase schema",
	} {
		if !strings.Contains(page, want) {
			t.Errorf("nextjs-saas.html is missing %q", want)
		}
	}
	if !strings.Contains(string(pages["templates/index.html"]), `href="expo-mobile.html"`) {
		t.Errorf("index does not link every template")
	}
	if !strings.Contains(string(pages["playground/index.html"]), "### F2.1.T2 — Clerk webhook syncs users into Supabase") {
		t.Errorf("playground does not start from the sample spec")
	}
}
