package config

import (
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

// ---------------------------------------------------------------------------
// The contract: where Go keeps a key, it must agree with Python
// ---------------------------------------------------------------------------

// testdata holds eight inputs and, beside each, the effective config the
// PYTHON loader produces for it (generated by make-golden.py). This test
// loads the same inputs here and compares every key the Go tree still models.
//
// It cannot be a whole-file diff: Go drops `findings`, `dashboard.kanban` and
// the multi-provider tunnel block, and adds `publish`. What must hold is
// narrower and more useful — for every key BOTH implementations have, the two
// loaders agree. A silent divergence in `concurrency.global_max` or
// `retry.backoff_seconds` would change dispatch behaviour on a project whose
// owner only swapped the binary.
func TestEffectiveConfigMatchesThePythonGoldens(t *testing.T) {
	inputs, err := filepath.Glob("testdata/*.input.yaml")
	if err != nil {
		t.Fatalf("glob testdata: %v", err)
	}
	if len(inputs) < 8 {
		t.Fatalf("found %d inputs, expected the 8 generated cases", len(inputs))
	}

	for _, in := range inputs {
		name := strings.TrimSuffix(filepath.Base(in), ".input.yaml")
		t.Run(name, func(t *testing.T) {
			goldenPath := filepath.Join("testdata", name+".effective.yaml")
			raw, err := os.ReadFile(goldenPath) // #nosec G304 -- fixed testdata path
			if err != nil {
				t.Fatalf("read golden: %v", err)
			}
			var py map[string]any
			if err := yaml.Unmarshal(raw, &py); err != nil {
				t.Fatalf("parse golden: %v", err)
			}

			res, err := Load(in, "testdata")
			if name == "backend-file" {
				// Python happily loads `backend: file`; Go refuses. That is
				// the one documented divergence, and it is the point of the
				// case, so assert the refusal instead of the values.
				if !errors.Is(err, ErrFileBackend) {
					t.Fatalf("loading a file-backend config returned %v, want ErrFileBackend", err)
				}
				return
			}
			if err != nil {
				t.Fatalf("Load: %v", err)
			}
			got := res.Config

			checks := []struct {
				path string
				got  any
			}{
				{"concurrency.global_max", got.Concurrency.GlobalMax},
				{"default_timeout_multiplier", got.DefaultTimeoutMult},
				{"budget.per_dispatch_usd", got.Budget.PerDispatchUSD},
				{"retry.max_attempts", got.Retry.MaxAttempts},
				{"retry.backoff_seconds", got.Retry.BackoffSeconds},
				{"retry.rate_limit_backoff_seconds", got.Retry.RateLimitBackoffSeconds},
				{"spec_root", got.SpecRoot},
				{"budgets_config", got.BudgetsConfig},
				{"budgets_preset", got.BudgetsPreset},
				{"typical_dispatch_tokens", got.TypicalDispatchToken},
				{"dispatch.worktree_mode", got.Dispatch.WorktreeMode},
				{"dispatch.base_branch", got.Dispatch.BaseBranch},
				{"vcs.provider", got.VCS.Provider},
				{"vcs.host", got.VCS.Host},
				{"vcs.auto_pr", got.VCS.AutoPR},
				{"vcs.ci_max_retries", got.VCS.CIMaxRetries},
				{"vcs.ci_poll_interval_s", got.VCS.CIPollIntervalS},
				{"github.test_command", got.GitHub.TestCommand},
				{"github.auto_merge", got.GitHub.AutoMerge},
				{"notifications.slack_webhook", got.Notifications.SlackWebhook},
				{"notifications.discord_webhook", got.Notifications.DiscordWebhook},
				{"notifications.timeout_s", got.Notifications.TimeoutS},
			}
			for _, c := range checks {
				want, ok := lookup(py, c.path)
				if !ok {
					t.Errorf("%s is absent from the Python golden — the key was "+
						"renamed or dropped upstream", c.path)
					continue
				}
				if !sameScalar(c.got, want) {
					t.Errorf("%s: Go says %v (%T), Python says %v (%T)",
						c.path, c.got, c.got, want, want)
				}
			}

			// The status labels are what the client reads; a divergence here
			// is visible in the stakeholder view.
			wantLabels, ok := lookup(py, "presentation.status_labels")
			if !ok {
				t.Fatal("presentation.status_labels missing from the golden")
			}
			wl, _ := wantLabels.(map[string]any)
			for k, want := range wl {
				if got.Presentation.StatusLabels[k] != want {
					t.Errorf("presentation.status_labels[%q]: Go %q, Python %v",
						k, got.Presentation.StatusLabels[k], want)
				}
			}
		})
	}
}

// lookup walks a dotted path through the decoded YAML.
func lookup(m map[string]any, path string) (any, bool) {
	cur := any(m)
	for _, seg := range strings.Split(path, ".") {
		mm, ok := cur.(map[string]any)
		if !ok {
			return nil, false
		}
		cur, ok = mm[seg]
		if !ok {
			return nil, false
		}
	}
	return cur, true
}

// sameScalar compares across YAML's int/float ambiguity: Python writes 5.0
// where Go holds a float64, and 6 where Go holds an int.
func sameScalar(got, want any) bool {
	switch g := got.(type) {
	case int:
		switch w := want.(type) {
		case int:
			return g == w
		case float64:
			return float64(g) == w
		}
	case float64:
		switch w := want.(type) {
		case int:
			return g == float64(w)
		case float64:
			return g == w
		}
	case string:
		w, ok := want.(string)
		return ok && g == w
	case bool:
		w, ok := want.(bool)
		return ok && g == w
	}
	return false
}

// ---------------------------------------------------------------------------
// The one refusal
// ---------------------------------------------------------------------------

func TestFileBackendIsAnErrorWithTheWayOut(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.yaml")
	write(t, path, "state:\n  backend: file\n")

	_, err := Load(path, dir)
	if !errors.Is(err, ErrFileBackend) {
		t.Fatalf("got %v, want ErrFileBackend", err)
	}
	// An error that only says "unsupported" leaves the operator stuck with a
	// project they cannot open. It has to name the command that fixes it.
	if !strings.Contains(err.Error(), "orch migrate") {
		t.Errorf("the error does not tell the operator what to run: %v", err)
	}
}

func TestBackendCases(t *testing.T) {
	cases := []struct {
		name    string
		yaml    string
		want    string
		wantErr bool
	}{
		{"absent defaults to sqlite", "", "sqlite", false},
		{"explicit sqlite", "state:\n  backend: sqlite\n", "sqlite", false},
		{"empty string defaults", "state:\n  backend: \"\"\n", "sqlite", false},
		{"case and space tolerated", "state:\n  backend: \" SQLite \"\n", "sqlite", false},
		{"file is refused", "state:\n  backend: file\n", "", true},
		{"nonsense is refused", "state:\n  backend: postgres\n", "", true},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			dir := t.TempDir()
			path := filepath.Join(dir, "config.yaml")
			write(t, path, c.yaml)
			res, err := Load(path, dir)
			if c.wantErr {
				if err == nil {
					t.Fatalf("expected an error, got backend %q", res.Config.State.Backend)
				}
				return
			}
			if err != nil {
				t.Fatalf("Load: %v", err)
			}
			if res.Config.State.Backend != c.want {
				t.Errorf("backend = %q, want %q", res.Config.State.Backend, c.want)
			}
		})
	}
}

// ---------------------------------------------------------------------------
// Dropped keys warn once and never fail
// ---------------------------------------------------------------------------

func TestDroppedKeysWarnButLoad(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.yaml")
	write(t, path, `
findings:
  publish_repo: "someone/somewhere"
  label: auto-reported
dashboard:
  board_url: "https://draw.example.invalid/editor/abc"
  profile: operator
spec_root: docs/specs
`)
	res, err := Load(path, dir)
	if err != nil {
		t.Fatalf("a config with dropped keys must still load: %v", err)
	}
	if res.Config.SpecRoot != "docs/specs" {
		t.Errorf("the keys we DO read were lost: spec_root = %q", res.Config.SpecRoot)
	}

	joined := strings.Join(res.Warnings, "\n")
	for _, want := range []string{"findings", "dashboard.board_url"} {
		if !strings.Contains(joined, want) {
			t.Errorf("no warning mentions %q:\n%s", want, joined)
		}
	}
	// One line for the whole `findings` section, not one per leaf.
	n := 0
	for _, w := range res.Warnings {
		if strings.HasPrefix(w, "ignoring `findings`") {
			n++
		}
	}
	if n != 1 {
		t.Errorf("expected a single warning for the findings section, got %d:\n%s", n, joined)
	}
}

func TestWarningsAreSortedAndDeduplicated(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.yaml")
	write(t, path, "zzz_unknown: 1\naaa_unknown: 2\nfindings:\n  publish_repo: x\n")
	res, err := Load(path, dir)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if len(res.Warnings) != 3 {
		t.Fatalf("want 3 warnings, got %d: %v", len(res.Warnings), res.Warnings)
	}
	for i := 1; i < len(res.Warnings); i++ {
		if res.Warnings[i-1] > res.Warnings[i] {
			t.Errorf("warnings are not sorted: %v", res.Warnings)
			break
		}
	}
}

func TestKnownKeysDoNotWarn(t *testing.T) {
	res, err := Load("testdata/packaged.input.yaml", "testdata")
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	// The packaged config is the fullest one we ship. Anything it contains
	// that Go does not read should be a DELIBERATE drop with an explanation,
	// not an "orch does not read this key" line.
	for _, w := range res.Warnings {
		if strings.Contains(w, "orch does not read this key") {
			t.Errorf("the packaged config produced an unexplained warning: %s", w)
		}
	}
}

// ---------------------------------------------------------------------------
// H-2 compatibility: a project-root dashboard.yaml still wins
// ---------------------------------------------------------------------------

func TestRootDashboardYAMLDeepMerges(t *testing.T) {
	dir := t.TempDir()
	cfg := filepath.Join(dir, ".orchestrator", "config.yaml")
	if err := os.MkdirAll(filepath.Dir(cfg), 0o750); err != nil {
		t.Fatal(err)
	}
	write(t, cfg, "dashboard:\n  profile: operator\n  summary_language: es\nspec_root: specs\n")
	write(t, filepath.Join(dir, "dashboard.yaml"),
		"dashboard:\n  summary_language: en\n  show_spend_to_stakeholder: true\n")

	res, err := Load(cfg, dir)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if res.Config.Dashboard.SummaryLanguage != "en" {
		t.Errorf("the override lost: summary_language = %q", res.Config.Dashboard.SummaryLanguage)
	}
	if !res.Config.Dashboard.ShowSpendToStakeholder {
		t.Error("a key present only in the override was dropped")
	}
	// Deep merge, not replace: a sibling the override did not mention stays.
	if res.Config.Dashboard.Profile != "operator" {
		t.Errorf("the merge clobbered a sibling key: profile = %q", res.Config.Dashboard.Profile)
	}
	if res.Config.SpecRoot != "specs" {
		t.Errorf("the merge clobbered a sibling section: spec_root = %q", res.Config.SpecRoot)
	}
	if len(res.Sources) != 2 {
		t.Errorf("Sources = %v, want both files", res.Sources)
	}
}

func TestMissingConfigIsNotAnError(t *testing.T) {
	dir := t.TempDir()
	res, err := Load(filepath.Join(dir, "nope.yaml"), dir)
	if err != nil {
		t.Fatalf("a missing config must fall back to defaults: %v", err)
	}
	if res.Config.SpecRoot != "specs" {
		t.Errorf("defaults not applied: spec_root = %q", res.Config.SpecRoot)
	}
	if len(res.Sources) != 0 {
		t.Errorf("Sources = %v, want empty", res.Sources)
	}
}

// ---------------------------------------------------------------------------
// Retry (F4.6)
// ---------------------------------------------------------------------------

func TestRetryPerClassOverridesTheScalars(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.yaml")
	write(t, path, `
retry:
  max_attempts: 2
  backoff_seconds: 5
  rate_limit_backoff_seconds: 60
  rate_limit:
    max_attempts: 5
  version_drift:
    max_attempts: 0
    escalate_model: true
`)
	res, err := Load(path, dir)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	r := res.Config.Retry

	if got := r.RateLimit.Attempts(r.MaxAttempts); got != 5 {
		t.Errorf("rate_limit.max_attempts = %d, want the per-class 5", got)
	}
	if got := r.RateLimit.Backoff(r.RateLimitBackoffSeconds); got != 60 {
		t.Errorf("rate_limit backoff = %v, want the scalar 60 to seed it", got)
	}
	// The reason RetryRule uses pointers: 0 means "never retry", which a
	// zero value could not distinguish from "unset".
	if got := r.VersionDrift.Attempts(r.MaxAttempts); got != 0 {
		t.Errorf("version_drift.max_attempts = %d, want an explicit 0", got)
	}
	if !r.VersionDrift.Escalate() {
		t.Error("version_drift.escalate_model was lost")
	}
	// A class with no block at all inherits.
	if got := r.Transient.Attempts(r.MaxAttempts); got != 2 {
		t.Errorf("transient inherited %d, want the scalar 2", got)
	}
	if r.Transient.Escalate() {
		t.Error("escalate_model defaulted to true")
	}
}

func TestRetryLegacyScalarsAloneStillWork(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.yaml")
	write(t, path, "retry:\n  backoff_seconds: 9\n  rate_limit_backoff_seconds: 120\n")
	res, err := Load(path, dir)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	r := res.Config.Retry
	if got := r.Transient.Backoff(r.BackoffSeconds); got != 9 {
		t.Errorf("transient backoff = %v, want the scalar 9", got)
	}
	if got := r.RateLimit.Backoff(r.RateLimitBackoffSeconds); got != 120 {
		t.Errorf("rate_limit backoff = %v, want the scalar 120", got)
	}
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

func TestStakeholderProfileWithoutATokenIsRefused(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.yaml")
	write(t, path, "dashboard:\n  profile: stakeholder\n")
	_, err := Load(path, dir)
	if err == nil {
		t.Fatal("a stakeholder dashboard with no token must not load — it 401s every request")
	}
	if !strings.Contains(err.Error(), "token") {
		t.Errorf("the error does not name the missing key: %v", err)
	}
}

// The tunnel is Cloudflare only. A config still choosing autossh or bore
// would otherwise start something else than it asks for, so it is refused
// with the one-line fix — and `tunnel.enabled` alone still loads.
func TestTunnelProviderKeysAreRefusedWithTheWayOut(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.yaml")
	for _, body := range []string{
		"tunnel:\n  enabled: true\n  provider: autossh\n",
		"tunnel:\n  provider: bore\n  args: [local, \"7420\"]\n",
		"tunnel:\n  command: autossh\n",
		"tunnel:\n  url_regex: x\n",
	} {
		write(t, path, body)
		_, err := Load(path, dir)
		if err == nil {
			t.Fatalf("%q loaded; the removed tunnel keys must be refused", body)
		}
		if !strings.Contains(err.Error(), "cloudflared") || !strings.Contains(err.Error(), "tunnel.enabled") {
			t.Errorf("the error does not say what to do: %v", err)
		}
	}

	write(t, path, "tunnel:\n  enabled: true\n  url_parse_timeout_s: 20\n")
	res, err := Load(path, dir)
	if err != nil {
		t.Fatalf("tunnel.enabled alone must load: %v", err)
	}
	if !res.Config.Tunnel.Enabled || res.Config.Tunnel.URLParseTimeoutS != 20 || len(res.Warnings) != 0 {
		t.Errorf("got %+v, warnings %v", res.Config.Tunnel, res.Warnings)
	}
}

func TestInvalidProfileIsRefused(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.yaml")
	write(t, path, "dashboard:\n  profile: admin\n  token: t\n")
	if _, err := Load(path, dir); err == nil {
		t.Fatal("dashboard.profile: admin must be refused")
	}
}

// ---------------------------------------------------------------------------
// Show
// ---------------------------------------------------------------------------

func TestShowPrintsValuesSourcesAndWarnings(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.yaml")
	write(t, path, "findings:\n  publish_repo: x\nspec_root: docs/specs\n")
	res, err := Load(path, dir)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	var buf bytes.Buffer
	if err := Show(&buf, res); err != nil {
		t.Fatalf("Show: %v", err)
	}
	out := buf.String()
	for _, want := range []string{"spec_root: docs/specs", "# sources", path, "# ignored keys", "findings"} {
		if !strings.Contains(out, want) {
			t.Errorf("Show output is missing %q:\n%s", want, out)
		}
	}
}

func TestShowSaysWhenEveryValueIsADefault(t *testing.T) {
	dir := t.TempDir()
	res, err := Load(filepath.Join(dir, "absent.yaml"), dir)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	var buf bytes.Buffer
	if err := Show(&buf, res); err != nil {
		t.Fatalf("Show: %v", err)
	}
	if !strings.Contains(buf.String(), "every value above is a default") {
		t.Errorf("Show did not say the config was absent:\n%s", buf.String())
	}
}

func write(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil { // #nosec G703 -- t.TempDir()
		t.Fatalf("write %s: %v", path, err)
	}
}

// ---------------------------------------------------------------------------
// Duplicate mapping keys: tolerated, because ours has one
// ---------------------------------------------------------------------------

// `orchestrator/config.yaml` defines `dashboard:` twice — once for
// summary_language and show_spend_to_stakeholder, and again 38 lines later
// for kanban and tunnel. PyYAML keeps the second, so the first block has
// never had any effect; editing the documented `summary_language` knob there
// does nothing, silently. `orch init` copied that file into every project
// scaffolded without a template.
//
// Go's yaml.v3 rejects duplicate keys, which is the better default. Applying
// it here would refuse to load configs orch itself wrote, so we match
// Python's last-wins and warn instead.
func TestDuplicateKeysFollowPythonAndWarn(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.yaml")
	write(t, path, `
dashboard:
  summary_language: en
  profile: operator
spec_root: specs
dashboard:
  summary_language: pt
`)
	res, err := Load(path, dir)
	if err != nil {
		t.Fatalf("a duplicate key must not fail the load: %v", err)
	}
	if res.Config.Dashboard.SummaryLanguage != "pt" {
		t.Errorf("summary_language = %q, want the LAST block's value, as PyYAML resolves it",
			res.Config.Dashboard.SummaryLanguage)
	}
	// The second block replaces the first wholesale — it is not a merge.
	// `profile` was only in the first, so it falls back to the default.
	if res.Config.Dashboard.Profile != "operator" {
		t.Errorf("profile = %q; the duplicate should have dropped the first "+
			"block entirely, leaving the default", res.Config.Dashboard.Profile)
	}
	found := false
	for _, w := range res.Warnings {
		if strings.Contains(w, "`dashboard`") && strings.Contains(w, "more than once") {
			found = true
		}
	}
	if !found {
		t.Errorf("the duplicate was silently accepted; warnings were:\n%s",
			strings.Join(res.Warnings, "\n"))
	}
}

func TestPackagedConfigLoadsDespiteItsDuplicate(t *testing.T) {
	res, err := Load("testdata/packaged.input.yaml", "testdata")
	if err != nil {
		t.Fatalf("the config orch itself ships must load: %v", err)
	}
	if res.Config.Concurrency.GlobalMax != 8 {
		t.Errorf("global_max = %d, want 8", res.Config.Concurrency.GlobalMax)
	}
	found := false
	for _, w := range res.Warnings {
		if strings.Contains(w, "more than once") {
			found = true
		}
	}
	if !found {
		t.Error("the packaged config's duplicate `dashboard:` key was not reported")
	}
}

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

func TestDefaultProjectIDSkipsGenericBasenames(t *testing.T) {
	cases := []struct{ root, want string }{
		{"/srv/example-project/orch", "orch"},
		{"/srv/example-project/orch/v2", "orch"},
		{"/srv/example-project/orch/src", "orch"},
		{"/srv/example-project/orch/apps", "orch"},
		{"/srv/billing-api", "billing-api"},
		{"/", "unknown"},
	}
	for _, c := range cases {
		if got := DefaultProjectID(c.root); got != c.want {
			t.Errorf("DefaultProjectID(%q) = %q, want %q", c.root, got, c.want)
		}
	}
}

func TestStateDirLayout(t *testing.T) {
	legacy := Paths{Root: "/p", ID: "proj", Layout: LayoutLegacy}
	if got, want := legacy.StateDir(), filepath.Join("/p", ".orchestrator", "state"); got != want {
		t.Errorf("legacy StateDir = %q, want %q", got, want)
	}
	ns := Paths{Root: "/p", ID: "proj", Layout: LayoutNamespaced}
	if got, want := ns.StateDir(), filepath.Join("/p", ".orchestrator", "state", "proj"); got != want {
		t.Errorf("namespaced StateDir = %q, want %q", got, want)
	}
}

func TestExplicitRootSelectsTheNamespacedLayout(t *testing.T) {
	dir := t.TempDir()
	p, err := ResolvePaths(dir, "", "")
	if err != nil {
		t.Fatalf("ResolvePaths: %v", err)
	}
	if p.Layout != LayoutNamespaced {
		t.Errorf("an explicit root gave layout %q, want namespaced", p.Layout)
	}
}

// Issue #84: a project previously run with an explicit root already has a
// namespaced directory. Missing that means `orch dashboard` started from
// inside the project reads an empty legacy database while the CLI writes the
// namespaced one — two truths, no error anywhere.
func TestExistingNamespacedStateIsDetected(t *testing.T) {
	dir := t.TempDir()
	id := DefaultProjectID(dir)
	nsDir := filepath.Join(dir, ".orchestrator", "state", id)
	if err := os.MkdirAll(nsDir, 0o750); err != nil {
		t.Fatal(err)
	}
	write(t, filepath.Join(nsDir, "orch.db"), "not really a database")

	t.Setenv("ORCH_PROJECT_ROOT", "")
	t.Chdir(dir)
	p, err := ResolvePaths("", "", "")
	if err != nil {
		t.Fatalf("ResolvePaths: %v", err)
	}
	if p.Layout != LayoutNamespaced {
		t.Errorf("layout = %q; existing namespaced state should have been detected", p.Layout)
	}
}

// Issue #229: `scripts/task-finish.sh` passes `--project-root .`, which is
// explicit, so it resolved the namespaced layout while `orch run` started from
// inside the project wrote the legacy one. The agent's verdict landed in a
// fresh database nobody read.
func TestExplicitRootKeepsExistingLegacyState(t *testing.T) {
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, ".orchestrator", "state"), 0o750); err != nil {
		t.Fatal(err)
	}
	write(t, filepath.Join(dir, ".orchestrator", "state", "orch.db"), "not really a database")

	p, err := ResolvePaths(dir, "", "")
	if err != nil {
		t.Fatalf("ResolvePaths: %v", err)
	}
	if p.Layout != LayoutLegacy {
		t.Errorf("layout = %q; an explicit root must keep the legacy state it already has", p.Layout)
	}
}

// Issue #229: an agent dispatched into `.worktrees/<ID>` runs `orch mcp` and
// the task scripts from there. `.orchestrator/` is gitignored, so resolving
// the worktree as the project bootstrapped a second database inside it.
func TestWorktreeResolvesToItsProject(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, ".orchestrator"), 0o750); err != nil {
		t.Fatal(err)
	}
	wt := filepath.Join(root, ".worktrees", "F1.T1")
	if err := os.MkdirAll(wt, 0o750); err != nil {
		t.Fatal(err)
	}

	t.Setenv("ORCH_PROJECT_ROOT", "")
	for name, arg := range map[string]string{"cwd": "", "explicit": wt} {
		t.Run(name, func(t *testing.T) {
			t.Chdir(wt)
			p, err := ResolvePaths(arg, "", "")
			if err != nil {
				t.Fatalf("ResolvePaths: %v", err)
			}
			if p.Root != root {
				t.Errorf("Root = %q, want the worktree's project %q", p.Root, root)
			}
			if p.ID != DefaultProjectID(root) {
				t.Errorf("ID = %q, want %q", p.ID, DefaultProjectID(root))
			}
		})
	}
}

// #249 moved worktrees out of the checkout, to `<project>.worktrees/<ID>`
// beside it. A person who cds into one, and `scripts/task-*.sh`, which pass
// `--project-root .`, still reach the project's database.
func TestSiblingWorktreeResolvesToItsProject(t *testing.T) {
	root := filepath.Join(t.TempDir(), "usebot")
	if err := os.MkdirAll(filepath.Join(root, ".orchestrator"), 0o750); err != nil {
		t.Fatal(err)
	}
	wt := filepath.Join(root+".worktrees", "F1.T1")
	if err := os.MkdirAll(wt, 0o750); err != nil {
		t.Fatal(err)
	}

	t.Setenv("ORCH_PROJECT_ROOT", "")
	t.Setenv("ORCH_PROJECT_ID", "")
	for name, arg := range map[string]string{"cwd": "", "explicit": wt, "dot": "."} {
		t.Run(name, func(t *testing.T) {
			t.Chdir(wt)
			p, err := ResolvePaths(arg, "", "")
			if err != nil {
				t.Fatalf("ResolvePaths: %v", err)
			}
			if p.Root != root {
				t.Errorf("Root = %q, want the worktree's project %q", p.Root, root)
			}
			if p.ID != "usebot" {
				t.Errorf("ID = %q, want usebot", p.ID)
			}
		})
	}
}

// A dispatched child gets ORCH_PROJECT_ROOT from the engine, so it resolves
// the project from wherever it runs, even a directory no path rule knows.
func TestProjectRootEnvWinsOverTheWorkingDirectory(t *testing.T) {
	root := t.TempDir()
	t.Setenv("ORCH_PROJECT_ROOT", root)
	t.Chdir(t.TempDir())
	p, err := ResolvePaths("", "", "")
	if err != nil {
		t.Fatalf("ResolvePaths: %v", err)
	}
	if p.Root != root {
		t.Errorf("Root = %q, want ORCH_PROJECT_ROOT's %q", p.Root, root)
	}
}

// A `.worktrees/` directory that is not orch's (no .orchestrator/ above it)
// is left alone, in either layout.
func TestUnrelatedWorktreesDirIsNotRewritten(t *testing.T) {
	base := t.TempDir()
	// A sibling layout whose "project" exists but is not orch's.
	if err := os.MkdirAll(filepath.Join(base, "app"), 0o750); err != nil {
		t.Fatal(err)
	}
	for _, wt := range []string{
		filepath.Join(base, ".worktrees", "x"),
		filepath.Join(base, "app.worktrees", "x"),
	} {
		if err := os.MkdirAll(wt, 0o750); err != nil {
			t.Fatal(err)
		}
		p, err := ResolvePaths(wt, "", "")
		if err != nil {
			t.Fatalf("ResolvePaths: %v", err)
		}
		if p.Root != wt {
			t.Errorf("Root = %q, want %q unchanged", p.Root, wt)
		}
	}
}

func TestEmptyNamespacedDirDoesNotFlipTheLayout(t *testing.T) {
	dir := t.TempDir()
	id := DefaultProjectID(dir)
	if err := os.MkdirAll(filepath.Join(dir, ".orchestrator", "state", id), 0o750); err != nil {
		t.Fatal(err)
	}
	t.Setenv("ORCH_PROJECT_ROOT", "")
	t.Chdir(dir)
	p, err := ResolvePaths("", "", "")
	if err != nil {
		t.Fatalf("ResolvePaths: %v", err)
	}
	if p.Layout != LayoutLegacy {
		t.Errorf("an empty directory flipped the layout to %q", p.Layout)
	}
}

func TestSQLitePathResolution(t *testing.T) {
	p := Paths{Root: "/p", ID: "proj", Layout: LayoutLegacy}
	cases := []struct{ configured, want string }{
		{"", filepath.Join("/p", ".orchestrator", "state", "orch.db")},
		{"custom.db", filepath.Join("/p", ".orchestrator", "state", "custom.db")},
		{"/elsewhere/orch.db", "/elsewhere/orch.db"},
	}
	for _, c := range cases {
		cfg := Defaults()
		cfg.State.SQLitePath = c.configured
		if got := p.SQLitePath(cfg); got != c.want {
			t.Errorf("SQLitePath(%q) = %q, want %q", c.configured, got, c.want)
		}
	}
}

func TestDivergentDatabasesDetected(t *testing.T) {
	dir := t.TempDir()
	p := Paths{Root: dir, ID: "proj", Layout: LayoutNamespaced}
	stateDir := filepath.Join(dir, ".orchestrator", "state")
	if err := os.MkdirAll(filepath.Join(stateDir, "proj"), 0o750); err != nil {
		t.Fatal(err)
	}
	if l, n := p.DivergentDatabases(); l != "" || n != "" {
		t.Errorf("reported divergence with no databases: %q %q", l, n)
	}
	write(t, filepath.Join(stateDir, "orch.db"), "x")
	if l, _ := p.DivergentDatabases(); l != "" {
		t.Error("reported divergence with only the legacy database")
	}
	write(t, filepath.Join(stateDir, "proj", "orch.db"), "x")
	l, n := p.DivergentDatabases()
	if l == "" || n == "" {
		t.Errorf("two coexisting databases were not reported: %q %q", l, n)
	}
}

// The project-relative paths every command resolves through. Trivial to
// write and trivial to get wrong — `.orchestrator/model_router.yaml` sits one
// level deeper than `tasks.json`, and a slip there is a file-not-found at
// dispatch time rather than at startup.
func TestProjectRelativePaths(t *testing.T) {
	root := t.TempDir()
	p := Paths{Root: root, ID: "proj", Layout: LayoutLegacy}

	cases := []struct {
		name string
		got  string
		want string
	}{
		{"tasks.json sits at the project root", p.TasksJSON(),
			filepath.Join(root, "tasks.json")},
		{"model_router.yaml sits under .orchestrator", p.RouterYAML(),
			filepath.Join(root, ".orchestrator", "model_router.yaml")},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if c.got != c.want {
				t.Errorf("got %q, want %q", c.got, c.want)
			}
		})
	}
}

// The layout decides where state goes, but never where tasks.json or the
// router live: those are per-project, not per-run.
func TestProjectRelativePathsIgnoreTheLayout(t *testing.T) {
	root := t.TempDir()
	legacy := Paths{Root: root, ID: "proj", Layout: LayoutLegacy}
	namespaced := Paths{Root: root, ID: "proj", Layout: LayoutNamespaced}

	if legacy.TasksJSON() != namespaced.TasksJSON() {
		t.Errorf("TasksJSON moved with the layout: %q vs %q",
			legacy.TasksJSON(), namespaced.TasksJSON())
	}
	if legacy.RouterYAML() != namespaced.RouterYAML() {
		t.Errorf("RouterYAML moved with the layout: %q vs %q",
			legacy.RouterYAML(), namespaced.RouterYAML())
	}
	if legacy.StateDir() == namespaced.StateDir() {
		t.Error("StateDir did NOT move with the layout, which is its whole job")
	}
}

// A project that kept its JSONL files but has no orch.db is still a project
// that was run with an explicit root — the layout has to follow.
func TestLegacyJSONLAlsoSelectsTheNamespacedLayout(t *testing.T) {
	dir := t.TempDir()
	id := DefaultProjectID(dir)
	nsDir := filepath.Join(dir, ".orchestrator", "state", id)
	if err := os.MkdirAll(nsDir, 0o750); err != nil {
		t.Fatal(err)
	}
	write(t, filepath.Join(nsDir, "events-run-1.jsonl"), "{}\n")

	t.Setenv("ORCH_PROJECT_ROOT", "")
	t.Chdir(dir)
	p, err := ResolvePaths("", "", "")
	if err != nil {
		t.Fatalf("ResolvePaths: %v", err)
	}
	if p.Layout != LayoutNamespaced {
		t.Errorf("layout = %q; a namespaced dir holding JSONL should count", p.Layout)
	}
}

// An unrelated file in the namespaced directory is not state.
func TestUnrelatedFilesDoNotSelectTheNamespacedLayout(t *testing.T) {
	dir := t.TempDir()
	id := DefaultProjectID(dir)
	nsDir := filepath.Join(dir, ".orchestrator", "state", id)
	if err := os.MkdirAll(nsDir, 0o750); err != nil {
		t.Fatal(err)
	}
	write(t, filepath.Join(nsDir, "README.md"), "notes\n")
	write(t, filepath.Join(nsDir, "prompts.jsonl"), "{}\n")

	t.Setenv("ORCH_PROJECT_ROOT", "")
	t.Chdir(dir)
	p, err := ResolvePaths("", "", "")
	if err != nil {
		t.Fatalf("ResolvePaths: %v", err)
	}
	if p.Layout != LayoutLegacy {
		t.Errorf("layout = %q; neither file is orch state", p.Layout)
	}
}
