package scaffold

import "strings"

// genericAgentsMD is the AGENTS.md a project gets when its template ships none
// — and every blank project.
//
// Ported from `_generate_agents_md`. It is the first thing an agent reads in a
// new project, so the two rules it has to land are the ones that cost real
// work when broken: runtime status lives in SQLite and not in tasks.json, and
// the `scripts/task-*.sh` helpers are how an agent reports back.
//
// The findings row is kept, unescaped pipes and all, because it is a real
// command and a markdown table needs them escaped. Dropping the row because
// the escaping is ugly would remove the only place the syntax is written down.
func genericAgentsMD(projectName string) string {
	dbPath := ".orchestrator/state/" + projectName + "/orch.db"

	var b strings.Builder
	b.WriteString(`# Orch Project Context

> Auto-generated by ` + "`orch init`" + `. Refresh with ` + "`orch atomize --apply`" + `.
> Read automatically by Claude Code and compatible agents at session start.

`)
	b.WriteString(aboutOrchBlock)
	b.WriteString(`## State backend

- SQLite: ` + "`" + dbPath + "`" + `
- ` + "`tasks_definition`" + ` (static): model, backend, deps, spec_ref, files, phase, estimate
- ` + "`tasks_runtime`" + ` (dynamic): status, attempts, last_model, last_backend
- ` + "`tasks.json`" + `: atomize input only — **never edit runtime status here**

## Check real task status

` + "```bash" + `
sqlite3 ` + dbPath + ` \
  "SELECT task_id, status, last_model FROM tasks_runtime \
   WHERE status != 'done' ORDER BY task_id;"
` + "```" + `

## Key commands

| Action | Command |
|--------|---------|
| View status | ` + "`orch status`" + ` |
| Set model/status | ` + "`orch task set --id TASK --model MODEL --status done`" + ` |
| Capture finding | ` + "`orch findings capture --type bug\\|feature\\|fix --about orch\\|project --summary \"...\" --evidence \"...\"`" + ` |
| Publish finding | ` + "`orch findings publish <id> --repo <repo> --yes`" + ` |
| Re-atomize | ` + "`orch atomize --apply`" + ` |

## Provider concurrency caps

| Provider | Max concurrent |
|----------|---------|
| claude | 3 |
| opencode | 6 |
| codex | 2 |

## Model router

See ` + "`.orchestrator/model_router.yaml`" + ` for backend→model mappings.
`)
	return b.String()
}

// aboutOrchBlock is shared with nothing today and kept separate anyway: it is
// the block every template's own AGENTS.md.tmpl reproduces, so when one of
// them drifts this is what to diff against.
const aboutOrchBlock = `## About orch (this project is orch-managed)

- ` + "`orch`" + ` walks ` + "`tasks.json`" + ` as a DAG and dispatches each task to
  Claude / Codex / OpenCode / Gemini in parallel.
- **CLI missing?** ` + "`curl -fsSL https://raw.githubusercontent.com/hectorcanaimero/orch/main/scripts/install.sh | sh`" + `
  or ` + "`brew install hectorcanaimero/orch/orch`" + ` (repo: <https://github.com/hectorcanaimero/orch>).
- **Never edit ` + "`tasks.json`" + ` status directly** — runtime state lives
  in SQLite. Use ` + "`orch task set --id ID --status STATUS`" + ` or one of
  the ` + "`scripts/task-*.sh`" + ` helpers.
- **Full agent context on demand**: if you use Claude Code, run
  ` + "`orch install-skills`" + ` once — the ` + "`/orch`" + ` skill loads only when the
  agent needs it (token-cheap). Otherwise ` + "`orch --help`" + ` is the source
  of truth.
- **Read-only inspection**: ` + "`orch status`" + `, ` + "`orch tasks`" + `,
  ` + "`orch events ID`" + `, ` + "`orch logs ID`" + `, ` + "`orch graph`" + `.

`
